spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/base?useTimezone=true&serverTimezone=UTC
    username: usuariodobanco
    password: P@$$w0rd
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  port: 8086
  servlet:
    context-path: /api
